### ISSUE TITLE
Add GameViewModel

### ISSUE THREAD

**Issue by ilyapaddubny** [ilyapaddubny/Who-Wants-to-Be-a-Millionaire#11]
Необходимо реализовать вьюмодель, где будет реализована логика процеса игры.

**Comment by ilyapaddubny** [comment]
@mabolotska реализует Логику вьюмодели (до делегирования), те работает только в файле вьюмодели. @oiau реализует логику таймера

**Comment by mabolotska** [comment]
#25 я добавила вьюмодель
