### ISSUE TITLE
Add GameViewController

### ISSUE THREAD

**Issue by ilyapaddubny** [ilyapaddubny/Who-Wants-to-Be-a-Millionaire#13]
![Image](https://github.com/ilyapaddubny/Who-Wants-to-Be-a-Millionaire/assets/33945343/6f3695d7-70d3-4881-a82a-dfe07e27d23f)

Делать согласно эскизу в фигме https://www.figma.com/file/Qve2XKkRSmMt88qRakXUSv/iPhone-Mockup-(Community)?node-id=0%3A5&mode=dev. Реализация немного может отличаться от проекта в фигме.

**Comment by smoozmy** [comment]
#6
